### ISSUE TITLE
Implement macro simplifications for missing features in cfn

### ISSUE THREAD

**Issue by marco-hoyer** [cfn-sphere/cfn-sphere#102]
It would be nice to have something like this for SNS subscriptions:

```
  subscription:
    Type: "Custom::CfnSphere::SnsSubscription"
    Properties:
      Protocol: "sqs"
      TopicArn: "|Ref|realtorTopicArn"
      Endpoint: "|GetAtt|realtorQueue|Arn"
```
