### ISSUE TITLE
Question about referring to individual stacks in a stack config

### ISSUE THREAD

**Issue by esc** [cfn-sphere/cfn-sphere#116]
Let's imagine we have the following stack config:

```
region: eu-west-1
stacks:
  deployer-elb:
    template-url: deployer-elb-template.yml
    timeout: 1200
deployer-instance-blue:
    template-url: deployer-instance-template.yml
    parameters:
        environment: blue
        deployerelbsg: "|Ref|deployer-elb.deployerelbsg"
  deployer-instance-green:
    template-url: deployer-instance-template.yml
    parameters:
        environment: green
        deployerelbsg: "|Ref|deployer-elb.deployerelbsg"
```

Now what I would like to do, is reference stacks individually in this config, e.g.:

```
$ cf delete  --yes stacks.yml:deployer-instance-blue
```

Is this possible? Is this even feasible?
