### ISSUE TITLE
Support json queries for file parameter values

### ISSUE THREAD

**Issue by marco-hoyer** [cfn-sphere/cfn-sphere#134]
If one references a json file as parameter value, it might not always contain the pure value for any reasons. We could support some kind of jq like query language allowing those users to query whatever they like from a json file and use it as input to a stack.

Example:
```
region: eu-west-1
stacks:
  my-stack:
    template-url: foo.yml
    parameters:
      myAccountIds: "|File|s3://my-bucket/my-accounts.json|.[].id"
```

This should return a list of account ids from a file like:
```JSON
[{
	"name": "a",
	"id": 123
}, {
	"name": "b",
	"id": 234
}]
```
