### ISSUE TITLE
Set parameter values by command line args

### ISSUE THREAD

**Issue by marco-hoyer** [cfn-sphere/cfn-sphere#14]
We would like to use cfn-sphere to deploy a new version of our application which is in fact a parameter in the cloudformation template. This should be done by a CI tool like Jenkins or Teamcity. It is not a good idea to directly modify the stacks.yml to write the new version. A possible solution would be to sync stacks with 
```bash
cf sync myapp.yml --parameter <stack>.version=10
```

when there is defined in the stack configuration:
```YAML
stacks:
  my-stack:
    parameters:
      version: %VERSION%
```
Where %VERSION% is to be replaced by something better.
