### ISSUE TITLE
Reference files as source for stack parameter values

### ISSUE THREAD

**Issue by marco-hoyer** [cfn-sphere/cfn-sphere#15]
I would like to be able to use files from filesystem/s3 or environment variables as input for stack parameters in stacks.yml in order to provide a bridge to CI systems providing an artifacts version f.e.

Example:
```YAML
stacks:
  my-stack:
    template-url: foo.yml
    parameters:
      app: myapp
      version: '|Ref|File|s3://my-bucket/latest-version.json'
      updater: '|Ref|Env|HOSTNAME'
```
