### ISSUE TITLE
YamlUserData macro creates broken yaml for lists

### ISSUE THREAD

**Issue by marco-hoyer** [cfn-sphere/cfn-sphere#150]
Indentation is broken for list values in a dict like f.e.
```
            "docker-compose": {
                "version": "2",
                "services": {
                    "grafana": {
                        "environment": {
                            "GF_SECURITY_ADMIN_PASSWORD": "|Ref|grafanaAdminPassword"
                        },
                        "ports": [
                            "3000:3000"
                        ],
                        "restart": "always"
                    }
                }
            }
```

It produces a yaml like:
```
docker-compose:
  version: 2
  services:
    grafana:
      ports:
- "3000": 3000
```
