### ISSUE TITLE
Reporting functionality for stack actions

### ISSUE THREAD

**Issue by marco-hoyer** [cfn-sphere/cfn-sphere#159]
There is a common pattern to provide services like ELK logging stacks or similar things used in several AWS accounts operated by different teams within bigger companies. The service owners suffer from a proper reporting showing them who is actually using their services and if the services use the latest artefact versions available. Cfn-Sphere could provide some value to the service owners by offering a callback functionality.

Everytime a stack update or deletion is executed, cfn-sphere could do a POST request to a webhook url configured in stack config containing some data describing the action.

Example stack config
```YAML
region: eu-west-1
stacks:
  fancy-logging-stack:
    template-url: s3://some-distribution-bucket/fancy-logging-template.json
    reporting-url: https://my-reporting-service/fancy-logging
    parameters:
      myLambdaFunctionVersion: "|File|s3://some-distribution-bucket/latest-version.txt"
      someOtherParameter: "foo"
```

How the post request content should look like:
```json
{
  "accountId": "123523423",
  "stackName": "fancy-logging-stack",
  "action": "update",
  "parameters": {
    "myLambdaFunctionVersion": 55,
    "someOtherParameter": "foo"
  }
}
```

Thinks to consider:

- [ ] Is it a good idea to pass secrets configured as parameter values in the stack config?
- [ ] Which other reporting targets should be supported? (Kinesis, S3, ...)
