### ISSUE TITLE
Allow List of |Ref| values in stack configuration

### ISSUE THREAD

**Issue by marco-hoyer** [cfn-sphere/cfn-sphere#51]
Cfg-Sphere does not support lists of `|Ref|` values but should. Example:
```
region: eu-west-1
stacks:
  my-stack:
    template-url: foo.json
    parameters:
      my-subnets:
        - "|Ref|vpc.subnetA"
        - "|Ref|vpc.subnetB"
```
