### ISSUE TITLE
cfn-sphere macro expansion not working for for Conditions in CFN template

### ISSUE THREAD

**Issue by schlomo** [cfn-sphere/cfn-sphere#67]
The following does not work:

```yaml
Conditions:
  hasJumpHostSG:
    Fn::Not:
      -
        Fn::Equals:
          - "|Ref|jumpHostSG"
          - NONE
```

because cfn-sphere does not replace the `|...|` with JSON maps.
