### ISSUE TITLE
converting native cfn 'joins' into sphere yml

### ISSUE THREAD

**Issue by FalkoBasner** [cfn-sphere/cfn-sphere#72]
Converting native cfn 'Fn:Join' does not work 

e.g.

CFN ORIGINAL:
```JSON
"cssDnsRecord": {
      "Type": "AWS::Route53::RecordSet",
      "Properties": {
        "HostedZoneName": {
          "Ref": "dnsBaseName"
        },
        "Comment": "Application Domain",
        "Name": {
          "Fn::Join": [
            ".",
            [
              "css",
              {
                "Ref": "dnsBaseName"
              }
            ]
          ]
        },
        "Type": "A",
        "AliasTarget" : {
          "HostedZoneId" : { "Fn::GetAtt" : ["elb", "CanonicalHostedZoneNameID"] },
          "DNSName" : { "Fn::GetAtt" : ["elb","CanonicalHostedZoneName"] }
        }
      }
    },
```
AFTER CONVERTING:
```YAML
cssDnsRecord:
    Properties:
      AliasTarget:
        DNSName:
          Fn::GetAtt:
          - elb
          - CanonicalHostedZoneName
        HostedZoneId:
          Fn::GetAtt:
          - elb
          - CanonicalHostedZoneNameID
      Comment: Application Domain
      HostedZoneName:
        Ref: dnsBaseName
      Name:
        Fn::Join:
        - .
        - - css
          - Ref: dnsBaseName
      Type: A
    Type: AWS::Route53::RecordSet
```
The converted yaml template should use correct '|Join|<seprator>' syntax
