### ISSUE TITLE
Allow to pass local file content as parameter value

### ISSUE THREAD

**Issue by jzastrow** [cfn-sphere/cfn-sphere#77]
It would be very helpful to allow to pass local file content as parameter values. Although a single value is limited to 4096 bytes it is possible to use multiple "Join" statements to create larger values (http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html).
No more manual S3 copy/read/load configuration/code snippets.

**Comment by marco-hoyer** [comment]
Hi @jzastrow, could you give a practical example to help me understand your need?

**Comment by jzastrow** [comment]
```yaml
  logging-elastic-template:
    template-url: "./templates/elastic-index-template.yml"
    parameters:
      templateBucket: "jzastrow-test"
      templatePath: "|File|elastic-index-template-1.json"
      elasticClusterEndpoint: "|Ref|logging-es.clusterEndpoint"
```
